RBS: Fix errors in write kind of:
  11) MemoryPointer allows writing as a sized int
      Failure/Error: m.write :uint32, 1

      RBS::Test::Tester::TypeError:
        TypeError: [FFI::Pointer#write] ArgumentTypeError: expected `bot` (value) but given `1`
      # /home/lars/.rvm/gems/ruby-3.3.0/gems/rbs-3.4.1/lib/rbs/test/tester.rb:158:in `call'
      # /home/lars/.rvm/gems/ruby-3.3.0/gems/rbs-3.4.1/lib/rbs/test/observer.rb:10:in `notify'
      # /home/lars/.rvm/gems/ruby-3.3.0/gems/rbs-3.4.1/lib/rbs/test/hook.rb:178:in `ensure in write__with__RBS_TEST_eb5149_4888829b'
      # /home/lars/.rvm/gems/ruby-3.3.0/gems/rbs-3.4.1/lib/rbs/test/hook.rb:178:in `write__with__RBS_TEST_eb5149_4888829b'
      # ./spec/ffi/rbx/memory_pointer_spec.rb:65:in `block (2 levels) in <top (required)>'
      # ------------------
      # --- Caused by: ---
      # RBS::Test::Tester::TypeError:
      #   TypeError: [FFI::AbstractMemory#put] ArgumentTypeError: expected `bot` (value) but given `1`
      #   /home/lars/.rvm/gems/ruby-3.3.0/gems/rbs-3.4.1/lib/rbs/test/tester.rb:158:in `call'