Use keyword arguments to fix error on ruby-head
ArgumentError: wrong number of arguments (given 2, expected 1)
Rakefile:152:in `block in <top (required)>'